version: "3"

services:
  telegram-mongo-db:
    image: "mongo"
    ports:
      - "127.0.0.1:27017:27017"
  statistic-mongo-db:
    image: "mongo"
    ports:
      - "127.0.0.1:27018:27017"
  statistic-service:
    image: "bot/statistic-service"
    ports:
      - "8080:8080"
    depends_on:
      - "statistic-mongo-db"
      - "telegram-service"
  telegram-service:
    image: "bot/telegram-service"
    ports:
      - "8081:8081"
    depends_on:
      - "telegram-mongo-db"